import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the shadcn CLI — upstream code, not ours to lint.
    "src/components/ui/**",
    // Build artifact copied in from packages/sdk.
    "public/sdk/**",
    // Generated by `prisma generate` — regenerated on every build.
    "src/generated/**",
  ]),

  {
    rules: {
      // Unused values are almost always a mistake; `_`-prefixed ones are deliberate.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // Keep type-only imports erasable so bundlers never pull server types into the client.
      "@typescript-eslint/consistent-type-imports": [
        "warn",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      // Server logging goes through explicit helpers; stray console noise should be visible.
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },

  {
    // Server modules and CLI scripts legitimately write to stdout.
    files: ["src/server/**/*.ts", "prisma/**/*.ts"],
    rules: { "no-console": "off" },
  },
]);

export default eslintConfig;
